Code           Description
'COMMONLAND'     "ha:Common land"
'AGRAREA'     "ha:Utilised agricultural area"
'B_1'     "ha:Arable land"
'B_1_1'     "ha:Cereals"
'B_1_1_1'     "ha:Common wheat and spelt"
'B_1_1_2'     "ha:Durum wheat"
'B_1_1_3'     "ha:Rye"
'B_1_1_4'     "ha:Barley"
'B_1_1_5'     "ha:Oats"
'B_1_1_6'     "ha:Grain maize"
'B_1_1_7'     "ha:Rice"
'B_1_1_99'     "ha:Other cereals"
'B_1_2'     "ha:Pulses - total"
'B_1_2_1'     "ha:Peas, field beans and sweet lupines"
'B_1_2_2'     "ha:Pulses other than peas, field beans and sweet lupines"
'B_1_3'     "ha:Potatoes"
'B_1_4'     "ha:Sugar beet"
'B_1_5'     "ha:Fodder roots and brassicas"
'B_1_6'     "ha:Industrial plants"
'B_1_6_1'     "ha:Tobacco"
'B_1_6_2'     "ha:Hops"
'B_1_6_3'     "ha:Cotton"
'B_1_6_4'     "ha:Rape and turnip"
'B_1_6_5'     "ha:Sunflower"
'B_1_6_6'     "ha:Soya"
'B_1_6_7'     "ha:Linseed (oil flax)"
'B_1_6_8'     "ha:Other oil seed crops"
'B_1_6_9'     "ha:Flax"
'B_1_6_10'     "ha:Hemp"
'B_1_6_11'     "ha:Other textile crops"
'B_1_6_12'     "ha:Aromatic, medicinal and culinary plants"
'B_1_6_99'     "ha:Industrial plants not mentioned elsewhere"
'B_1_7'     "ha:Fresh vegetables, melons, strawberries"
'B_1_7_1'     "ha:Outdoor:Fresh vegetables, melons, strawberries"
'B_1_7_1_1'     "ha:Open field:Outdoor:Fresh vegetables, melons, strawberries"
'B_1_7_1_2'     "ha:Market gardening:Outdoor:Fresh vegetables, melons, strawberries"
'B_1_7_2'     "ha:Under glass:Fresh vegetables, melons, strawberries"
'B_1_8'     "ha:Flowers and ornemental plants"
'B_1_8_1'     "ha:Outdoor:Flowers and ornemental plants"
'B_1_8_2'     "ha:Under glass:Flowers and ornemental plants"
'B_1_9'     "ha:Forage plants - total"
'B_1_9_1'     "ha:Forage plants - temporary grass"
'B_1_9_2'     "ha:Total:Other green fodder:Forage plants"
'B_1_9_2_1'     "ha:Green maize:Other green fodder:Forage plants"
'B_1_9_2_2'     "ha:Other forage plants: leguminous plants"
'B_1_9_2_99'     "ha:Other green fodder - other than green maize"
'B_1_10'     "ha:Seeds and seedlings"
'B_1_11'     "ha:Other crops on arable land"
'B_1_12'     "ha:Fallow land - Total"
'B_1_12_1'     "ha:Fallow land without subsidies"
'B_1_12_2'     "ha:Fallow land subject to payment of subsidies with no economic use"
'B_2'     "ha:Kitchen gardens"
'B_3'     "ha:Total:Permanent grassland and meadow"
'B_3_1'     "ha:Pasture and meadow:Permanent grassland and meadow"
'B_3_2'     "ha:Rough grazings:Permanent grassland and meadow"
'B_3_3'     "ha:Permanent grassland and meadow - not used for production, eligible for subsidies"
'B_3_99'     "ha:Fodder  crops and grass"
'B_4'     "ha:Permanent crops"
'B_4_1'     "ha:Fruit and berry plantations - total"
'B_4_1_1'     "ha:Fruit and berry plantations - Fruit species"
'B_4_1_1_1'     "ha:Fruit species of temperate climate zones"
'B_4_1_1_2'     "ha:Fruit species of subtropical climate zones"
'B_4_1_2'     "ha:Berry species"
'B_4_1_3'     "ha:Nuts:Fruit and berry plantations"
'B_4_1_99_1'     "ha:Temperate climate:Fruit and berry plantations - until 2007"
'B_4_1_99_2'     "ha:Subtropical climate:Fruit and berry plantations - until 2007"
'B_4_2'     "ha:Citrus plantations"
'B_4_3'     "ha:Olive plantations - total"
'B_4_3_1'     "ha:Olive plantations - table olives"
'B_4_3_2'     "ha:Olive plantations - oil production"
'B_4_4'     "ha:Vineyards - total"
'B_4_4_1'     "ha:Vineyards - quality wine"
'B_4_4_2'     "ha:Vineyards - other wines"
'B_4_4_3'     "ha:Vineyards - table grapes"
'B_4_4_4'     "ha:Vineyards - raisins"
'B_4_5'     "ha:Nurseries"
'B_4_6'     "ha:Other permanent crops"
'B_4_6_1'     "Hectares of christmas trees"
'B_4_6_2'     "Hectares of other permanent crops other than christmas trees"
'B_4_7'     "ha:Permanent crops under glass"
'B_5'     "ha:Other area -Total"
'B_5_1'     "ha:Unutilised agricultural land"
'B_5_2'     "ha:Wooded area"
'B_5_2_1'     "ha:Wooded area - with short rotation"
'B_5_3'     "ha:Other land"
'B_6_1'     "ha:Mushrooms"
'B_6_2_1'     "ha:Total irrigable area"
'B_6_2_2'     "ha:Irrigated once a year:Total"
'B_6_3'     "ha:Energy crops"
'B_6_3_1'     "ha:Energy crops on set-aside area"
'B_6_4'     "ha:Genetically modified crops"
'B_1_345'     "ha:Root crops"
'B_1_6_7_11'     "ha:Other oil-seed or fibre crops"
'B_1_9_2_2_99'     "ha:Other forage plants (incl. leguminous plants)"
'B_1_10_11'     "ha:Seeds and seedlings and other crops on arable land"
'B_477282'     "ha:Under glass:Vegetables, flowers and permanent crops"
'B_5_1_5_3'     "ha:Unutilised agricultural land and other areas"
'B_6_2_2_99'     "ha: Irrigated area incl. kithen gardens and area under glass"

#*  --------------------------------------------------------------------------------------------
#*  Livestock (heads) codes in gridded FSS 2010 data obtained from Oscar Gomez on 11.08.2017
#*  --------------------------------------------------------------------------------------------
#'C_1H'     "head:Equidae"
#'C_2H'     "head:Cattle - total"
#'C_2_1H'     "head:Bovine <1 year old - total"
#'C_2_2H'     "head:Bovine 1-<2 years - males"
#C_2_3H'     "head:Bovine 1-<2 years - females"
#'C_2_2_3H'     "head:Bovine 1-<2 years - total"
#'C_2_4H'     "head:Bovine 2 years and older - males"
#'C_2_5H'     "head:Heifers, 2 years and older"
#'C_2_6H'     "head:Dairy cows"
#'C_2_99H'     "head:Other cows, bovine 2 years old and over"
#'C_2_6_99H'     "head: Total cows"
##'C_25699H'     "head: Total bovines 2 years and older - females"
#'#C_3H'     "head:Sheep and goats - total"
#'C_3_1H'     "head:Sheep - total"
#'C_3_1_1H'     "head:Sheep - breeding females"
#'C_3_1_99H'     "head:Sheep - others"
#'C_3_2H'     "head:Goats"
#'C_3_2_1H'     "head:Goats - breeding females"
#'C_3_2_99H'     "head:Goats - others"
#'C_4H'     "head:Pigs"
#'C_4_1H'     "head:Pigs - piglets under 20 kg"
#'C_4_2H'     "head:Pigs - breeding sows over 50 kg"
#'C_4_99H'     "head:Pigs - others"
#'C_5H'     "head:Poultry"
#'C_5_1H'     "head:Poultry-broilers"
#'C_5_2H'     "head:Laying hens"
#'C_5_3H'     "head:Poultry-others"
#'C_5_3_1H'     "head:Turkeys"
#'C_5_3_2H'     "head:Ducks"
#'C_5_3_3H'     "head:Geese"
#'C_5_3_4H'     "head:Ostriches"
#'C_5_3_99H'     "head:Other poultry"
#'C_6H'     "head:Rabbits (breeding females)"

#$*  --------------------------------------------------------------------------------------------
#*#  Livestock (in LSU) codes in gridded FSS 2010 data obtained from Oscar Gomez on 11.08.2017
#*  --------------------------------------------------------------------------------------------
'C_LIVEST_L'     "Livestock in LSU"
'C_1L'     "LSU:Equidae"
'C_2L'     "LSU:Cattle"
'C_2_1L'     "LSU:Bovine <1 year old - total"
'C_2_2L'     "LSU:Bovine 1-<2 years - males"
'C_2_3L'     "LSU:Bovine 1-<2 years - females"
'C_2_2_3L'     "LSU:Bovine 1-<2 years - total"
'C_2_4L'     "LSU:Bovine 2 years and older - males"
'C_2_5L'     "LSU:Heifers, 2 years and older"
'C_2_6L'     "LSU:Dairy cows"
'C_2_99L'     "LSU:Other cows, bovine 2 years old and over"
'C_2_6_99L'     "LSU:: Total cows"
'C_2_1_2_5L'     "LSU:Bovine, other than cows (J/2 to J/6)"
'C_21399L'     "LSU:Ruminant (J/02 to J/10)"
'C_25699L'     "LSU: Total bovines 2 years and older - females"
'C_3L'     "LSU:Sheep and goats - total"
'C_3_1L'     "LSU:Sheep - total"
'C_3_1_1L'     "LSU:Sheep - breeding females"
'C_3_1_99L'     "LSU:Sheep - others"
'C_3_2L'     "LSU:Goats"
'C_3_2_1L'     "LSU:Goats - breeding females"
'C_3_2_99L'     "LSU:Goats - others"
'C_3_1_3_2L'     "LSU:Sheep and goats (!!!!obsolete as it is the same as C_3L!!!!)"
'C_4L'     "LSU:Pigs"
'C_4_1L'     "LSU:Pigs - piglets under 20 kg"
'C_4_2L'     "LSU:Pigs - breeding sows over 50 kg"
'C_4_99L'     "LSU:Pigs - others"
'C_5L'     "LSU:Poultry"
'C_5_1L'     "LSU:Poultry - broilers"
'C_5_2L'     "LSU:Laying hens"
'C_5_3L'     "LSU:Poultry - others"
'C_6L'     "LSU:Rabbits (breeding females)"
'C_1_3L'     "LSU:Grazing livestock"
'C_4_5_6L'     "LSU:Pigs, poultry or rabbits (breeding females)"

#* Livestock additional information in gridded FSS 2010 data obtained from Oscar Gomez on 11.08.2017

'LIVESTOCK'     "ha:of holdings with Livestock"
'C_1_3_HAL'     "LSU:Grazing livestock per rough grazing<1"
